# Route the ALSA default device to the first HDMI port of the Raspberry Pi.
pcm.!default {
    type plug
    slave.pcm "hdmi0"
}
pcm.hdmi0 {
    type hw
    card vc4hdmi0
    device 0
}
ctl.!default {
    type hw
    card vc4hdmi0
}
